---
name: Release

on:
  push:
    branches:
      - main

jobs:
  docker:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: bump the version
        id: bumper
        uses: tomerfi/version-bumper-action@1.1.3

      - name: Build and push
        uses: elgohr/Publish-Docker-Github-Action@v4
        with:
          name: mrdoodles/sam-code-signing-config
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
          dockerfile: ./Dockerfile
          tags: "latest, v${{ steps.bumper.outputs.new_version }}, v${{ steps.bumper.outputs.major_part }}, v${{ steps.bumper.outputs.major_part }}.${{ steps.bumper.outputs.minor_part }}"

  action:
    name: Build and release action
    needs: [docker]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: bump the version
        id: bumper
        uses: tomerfi/version-bumper-action@1.1.3

      - name: Create a release name
        id: release_name
        uses: actions/github-script@v6
        with:
          script: |
            var retval = '${{ steps.bumper.outputs.new_version }}'
            if ('${{ github.event.inputs.title }}') {
              retval = retval.concat(' - ${{ github.event.inputs.title }}')
            }
            core.setOutput('value', retval)
      - name: Create a release
        id: gh_release
        uses: actions/github-script@v6
        with:
          script: |
            const repo_name = context.payload.repository.full_name
            const response = await github.request('POST /repos/' + repo_name + '/releases', {
              tag_name: '${{ steps.bumper.outputs.new_version }}',
              name: '${{ steps.release_name.outputs.value }}',
              generate_release_notes: true
            })
            core.setOutput('html_url', response.data.html_url)

      - name: Test for major version change
        id: version_count
        run: echo "::set-output name=count::$(fgrep -c sam-code-signing-config@v${{ steps.bumper.outputs.major_part }} ) README.md"

      - name: Update usage example
        if: steps.version_count.outputs.count == 0
        run: |
          sed -i 's|uses\: rusty-actions/sam-code-signing-config@.*|uses\: rusty-actions/sam-code-signing-config@v${{ steps.bumper.outputs.major_part }}|g' README.md

      - name: Configure git
        if: steps.version_count.outputs.count == 0
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Push modifications
        if: steps.version_count.outputs.count == 0
        run: |
          if [[ ! $(git diff --quiet) ]]; then
            git add README.md
            git commit -m "docs: update README usage section with v${{ steps.bumper.outputs.major_part }} [skip ci]"
            git push
          fi